# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PaWPal' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  def pawpal_pods
  # Pods for PaWPal
    pod 'Firebase', '>= 2.5.1'
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Charts', '2.1.6'
  end
  
  pawpal_pods  

  target 'PaWPalTests' do
    inherit! :search_paths
    # Pods for testing
    pawpal_pods
  end

  target 'PaWPalUITests' do
    inherit! :search_paths
    # Pods for testing
    pawpal_pods
  end

end
